### ISSUE TITLE
version requirement error

### ISSUE THREAD

**Issue by superdude808** [MinecraftModDevelopmentMods/Tinkers-Golems-Addon#2]
is asking for version 1.12.2-2.12.0.116 which doesn't exist. 
when the current latest version is 1.12.2-2.12.0.115

**Comment by superdude808** [comment]
probably a typo in the code no real harm done

**Comment by skyjay1** [comment]
My apologies, I was using the latest version of Tinkers from their Maven repository and didn't realize it hasn't been pushed to Forge. I've fixed the error and uploaded a new file. Sorry for the inconvenience.
