### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Univizum** [MinecraftModDevelopmentMods/Tinkers-Golems-Addon#3]
heres the crash log thanks
https://paste.dimdev.org/ifoxahekup.mccrash

**Comment by skyjay1** [comment]
Crash is due to a change in Extra Golems API, I'll go in and update Tinkers Golems. Thank you.

**Comment by skyjay1** [comment]
Fixed in Tinkers' Golems Addon 7.1.5-0
